CREATE TABLE scores (
  uid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  score UNSIGNED BIG INT NOT NULL,
  player INTEGER NOT NULL,
  FOREIGN KEY (player) REFERENCES players (uid) ON UPDATE CASCADE ON DELETE CASCADE
);
